-- Unable to render TABLE DDL for object PRCQA.PRCBUILD_DR_TESTSET with DBMS_METADATA attempting internal generator.
CREATE INDEX PRCQA.PRCBUILD_DR_TESTSET_330DF8AA ON PRCQA.PRCBUILD_DR_TESTSET (FAMILY_ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX PRCQA.SYS_C0080896 ON PRCQA.PRCBUILD_DR_TESTSET (ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE PRCQA.PRCBUILD_DR_TESTSET
ADD CONSTRAINT SYS_C0080897 FOREIGN KEY
(
  FAMILY_ID 
)
REFERENCES PRCQA.PRCBUILD_DR_FAMILY
(
  ID 
)
DEFERRABLE INITIALLY DEFERRED
ENABLECREATE TABLE PRCQA.PRCBUILD_DR_TESTSET 
(
  ID NUMBER(11, 0) NOT NULL 
, FAMILY_ID NUMBER(11, 0) NOT NULL 
, TESTSET_QC_ID NVARCHAR2(500) 
, TESTSET_NAME NVARCHAR2(500) 
, TESTSET_DISPLAY_NAME NVARCHAR2(500) 
, TESTSET_LOCATION NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT SYS_C0080896 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
