-- Unable to render TABLE DDL for object PRCQA.PRCBUILD_DR_DAILYRUN with DBMS_METADATA attempting internal generator.
--  1.Creating Index
CREATE INDEX PRCQA.PRCBUILD_DR_DAILYRUN_57721724 ON PRCQA.PRCBUILD_DR_DAILYRUN (TEST_ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL

--  1.Creating Index
CREATE INDEX PRCQA.PRCBUILD_DR_DAILYRUN_DR_DATE ON PRCQA.PRCBUILD_DR_DAILYRUN (DR_DATE ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL

--  Creating Unique Index
CREATE UNIQUE INDEX PRCQA.SYS_C0080910 ON PRCQA.PRCBUILD_DR_DAILYRUN (ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
)


NOPARALLEL

--  Creating Table
CREATE TABLE PRCQA.PRCBUILD_DR_DAILYRUN
(
  ID NUMBER(11, 0) NOT NULL 
, TEST_ID NUMBER(11, 0) NOT NULL 
, DR_DATE NVARCHAR2(500) 
, DR_EXECUTED_TODAY NUMBER(1, 0) NOT NULL 
, DR_STATUS NVARCHAR2(500) 
, DR_CATEGORY_OF_FAILURE NVARCHAR2(500) 
, DR_BUG_NUMBER NVARCHAR2(500) 
, DR_NEW_BUG NVARCHAR2(500) 
, DR_REASON NVARCHAR2(2000) 
, DR_RERUN_STATUS NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, DR_NOTES NVARCHAR2(2000) 
, CONSTRAINT SYS_C0080910 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL

--  Altering Table
ALTER TABLE PRCQA.PRCBUILD_DR_DAILYRUN
ADD CONSTRAINT SYS_C0080911 FOREIGN KEY
(
  TEST_ID 
)

-- References
REFERENCES PRCQA.PRCBUILD_DR_TEST
(
  ID 
)
DEFERRABLE INITIALLY DEFERRED
ENABLE

--  Altering Table
ALTER TABLE PRCQA.PRCBUILD_DR_DAILYRUN
ADD CONSTRAINT SYS_C0080909 CHECK 
("DR_EXECUTED_TODAY" IN (0,1))
ENABLE
