-- Unable to render TABLE DDL for object PRCQA.PRCBUILD_DR_TESTRUN with DBMS_METADATA attempting internal generator.
CREATE INDEX PRCQA.PRCBUILD_DR_TESTRUN_2A919796 ON PRCQA.PRCBUILD_DR_TESTRUN (DAILYRUN_ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX PRCQA.SYS_C0080917 ON PRCQA.PRCBUILD_DR_TESTRUN (ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE PRCQA.PRCBUILD_DR_TESTRUN
ADD CONSTRAINT SYS_C0080918 FOREIGN KEY
(
  DAILYRUN_ID 
)
REFERENCES PRCQA.PRCBUILD_DR_DAILYRUN
(
  ID 
)
DEFERRABLE INITIALLY DEFERRED
ENABLECREATE TABLE PRCQA.PRCBUILD_DR_TESTRUN 
(
  ID NUMBER(11, 0) NOT NULL 
, DAILYRUN_ID NUMBER(11, 0) NOT NULL 
, TR_NAME NVARCHAR2(500) 
, TR_STATUS NVARCHAR2(500) 
, TR_HOST NVARCHAR2(500) 
, TR_DURATION NVARCHAR2(500) 
, TR_EXEC_DATE TIMESTAMP(6) NOT NULL 
, TR_TESTER NVARCHAR2(500) 
, TR_REPORT_LOCATION NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, TR_FAAT_LABEL NVARCHAR2(500) 
, TR_INTERNAL_QC_RUN_ID NVARCHAR2(500) 
, CONSTRAINT SYS_C0080917 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
