-- Unable to render TABLE DDL for object PRCQA.PRCBUILD_DR_FAMILY_CONFIG with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX PRCQA.SYS_C0088969 ON PRCQA.PRCBUILD_DR_FAMILY_CONFIG (ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE PRCQA.PRCBUILD_DR_FAMILY_CONFIG 
(
  ID NUMBER(11, 0) NOT NULL 
, FC_FAMILY_NAME NVARCHAR2(500) 
, FC_BUG_TABLE NCLOB 
, CONSTRAINT SYS_C0088969 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (FC_BUG_TABLE) STORE AS SYS_LOB0000284216C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
)
