-- Unable to render TABLE DDL for object PRCQA.PRCBUILD_DR_FAMILY with DBMS_METADATA attempting internal generator.
ALTER TABLE PRCQA.PRCBUILD_DR_FAMILY
ADD CONSTRAINT SYS_C0080891 FOREIGN KEY
(
  ENV_ID 
)
REFERENCES PRCQA.PRCBUILD_DR_ENV
(
  ID 
)
DEFERRABLE INITIALLY DEFERRED
ENABLEALTER TABLE PRCQA.PRCBUILD_DR_FAMILY
ADD CONSTRAINT SYS_C0080889 CHECK 
("FAMILY_MONITOR" IN (0,1))
ENABLE
ALTER TABLE PRCQA.PRCBUILD_DR_FAMILY
ADD CONSTRAINT SYS_C0088385 CHECK 
("FAMILY_BUG_FROM_QC" IN (0,1))
ENABLECREATE TABLE PRCQA.PRCBUILD_DR_FAMILY 
(
  ID NUMBER(11, 0) NOT NULL 
, ENV_ID NUMBER(11, 0) NOT NULL 
, FAMILY_NAME NVARCHAR2(500) 
, FAMILY_LOCATION NVARCHAR2(500) 
, FAMILY_MONITOR NUMBER(1, 0) NOT NULL 
, FAMILY_DR_SYNC NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, FAMILY_ENV_FILE NVARCHAR2(500) 
, FAMILY_BUG_FROM_QC NUMBER(1, 0) DEFAULT '0' NOT NULL 
, CONSTRAINT SYS_C0080890 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX PRCQA.PRCBUILD_DR_FAMILY_291D355E ON PRCQA.PRCBUILD_DR_FAMILY (ENV_ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX PRCQA.SYS_C0080890 ON PRCQA.PRCBUILD_DR_FAMILY (ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
