-- Unable to render TABLE DDL for object PRCQA.PRCBUILD_DR_TEST with DBMS_METADATA attempting internal generator.
CREATE INDEX PRCQA.PRCBUILD_DR_TEST_2F861C8D ON PRCQA.PRCBUILD_DR_TEST (TESTSET_ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX PRCQA.SYS_C0080902 ON PRCQA.PRCBUILD_DR_TEST (ID ASC) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE PRCQA.PRCBUILD_DR_TEST
ADD CONSTRAINT SYS_C0080903 FOREIGN KEY
(
  TESTSET_ID 
)
REFERENCES PRCQA.PRCBUILD_DR_TESTSET
(
  ID 
)
DEFERRABLE INITIALLY DEFERRED
ENABLECREATE TABLE PRCQA.PRCBUILD_DR_TEST 
(
  ID NUMBER(11, 0) NOT NULL 
, TESTSET_ID NUMBER(11, 0) NOT NULL 
, TEST_NAME NVARCHAR2(500) 
, TEST_DISPLAY_NAME NVARCHAR2(500) 
, TEST_TYPE NVARCHAR2(500) 
, TEST_QC_ID NVARCHAR2(500) 
, TEST_PRODUCT NVARCHAR2(500) 
, TEST_PRODUCT_CODE NVARCHAR2(500) 
, TEST_OWNER NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, TEST_DELIVERY_CATEGORY VARCHAR2(500 BYTE) 
, CONSTRAINT SYS_C0080902 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PRCQA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
