

-- From PRCBUILD_DR_COMMENT.sql
CREATE TABLE GEMDB_TEST.PRCBUILD_DR_COMMENT 
(
  ID NUMBER(11, 0) NOT NULL 
, FAMILY_ID NUMBER(11, 0) NOT NULL 
, DR_DATE NVARCHAR2(500) 
, DR_COMMENTS NVARCHAR2(2000) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT SYS_C0081158 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
)

--  From  PRCBUILD_DR_DAILYRUN.sql
CREATE TABLE GEMDB_TEST.PRCBUILD_DR_DAILYRUN
(
    ID NUMBER(11, 0) NOT NULL
  , TEST_ID NUMBER(11, 0) NOT NULL
  , DR_DATE NVARCHAR2(500)
  , DR_EXECUTED_TODAY NUMBER(1, 0) NOT NULL
  , DR_STATUS NVARCHAR2(500)
  , DR_CATEGORY_OF_FAILURE NVARCHAR2(500)
  , DR_BUG_NUMBER NVARCHAR2(500)
  , DR_NEW_BUG NVARCHAR2(500)
  , DR_REASON NVARCHAR2(2000)
  , DR_RERUN_STATUS NVARCHAR2(500)
  , LAST_UPDATED_BY NVARCHAR2(500)
  , LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL
  , CREATED_BY NVARCHAR2(500)
  , CREATED_DATE TIMESTAMP(6) NOT NULL
  , DR_NOTES NVARCHAR2(2000)
  , CONSTRAINT SYS_C0080910 PRIMARY KEY
  (
    ID
  )
ENABLE
)


CREATE TABLE GEMDB_TEST.PRCBUILD_DR_DAILYRUN 
(
  ID NUMBER(11, 0) NOT NULL 
, TEST_ID NUMBER(11, 0) NOT NULL 
, DR_DATE NVARCHAR2(500) 
, DR_EXECUTED_TODAY NUMBER(1, 0) NOT NULL 
, DR_STATUS NVARCHAR2(500) 
, DR_CATEGORY_OF_FAILURE NVARCHAR2(500) 
, DR_BUG_NUMBER NVARCHAR2(500) 
, DR_NEW_BUG NVARCHAR2(500) 
, DR_REASON NVARCHAR2(2000) 
, DR_RERUN_STATUS NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, DR_NOTES NVARCHAR2(2000) 
, CONSTRAINT SYS_C0080910 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
)

CREATE TABLE GEMDB_TEST.PRCBUILD_DR_FAMILY_CONFIG
(
    ID NUMBER(11, 0) NOT NULL
  , FC_FAMILY_NAME NVARCHAR2(500)
  , FC_BUG_TABLE NCLOB
  , CONSTRAINT SYS_C0088969 PRIMARY KEY
  (
    ID
  )
ENABLE
)

CREATE TABLE GEMDB_TEST.PRCBUILD_DR_TEST
(
    ID NUMBER(11, 0) NOT NULL
  , TESTSET_ID NUMBER(11, 0) NOT NULL
  , TEST_NAME NVARCHAR2(500)
  , TEST_DISPLAY_NAME NVARCHAR2(500)
  , TEST_TYPE NVARCHAR2(500)
  , TEST_QC_ID NVARCHAR2(500)
  , TEST_PRODUCT NVARCHAR2(500)
  , TEST_PRODUCT_CODE NVARCHAR2(500)
  , TEST_OWNER NVARCHAR2(500)
  , LAST_UPDATED_BY NVARCHAR2(500)
  , LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL
  , CREATED_BY NVARCHAR2(500)
  , CREATED_DATE TIMESTAMP(6) NOT NULL
  , TEST_DELIVERY_CATEGORY VARCHAR2(500 BYTE)
  , CONSTRAINT SYS_C0080902 PRIMARY KEY
  (
    ID
  )
ENABLE
)


CREATE TABLE GEMDB_TEST.PRCBUILD_DR_TESTRUN 
(
  ID NUMBER(11, 0) NOT NULL 
, DAILYRUN_ID NUMBER(11, 0) NOT NULL 
, TR_NAME NVARCHAR2(500) 
, TR_STATUS NVARCHAR2(500) 
, TR_HOST NVARCHAR2(500) 
, TR_DURATION NVARCHAR2(500) 
, TR_EXEC_DATE TIMESTAMP(6) NOT NULL 
, TR_TESTER NVARCHAR2(500) 
, TR_REPORT_LOCATION NVARCHAR2(500) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, TR_FAAT_LABEL NVARCHAR2(500) 
, TR_INTERNAL_QC_RUN_ID NVARCHAR2(500) 
, CONSTRAINT SYS_C0080917 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 