-- Unable to render TABLE DDL for object GEMDB_TEST.PRCBUILD_DR_COMMENT with DBMS_METADATA attempting internal generator.

--  Creating Index
CREATE INDEX GEMDB_TEST.PRCBUILD_DR_COMMENT_330DF8AA ON GEMDB_TEST.PRCBUILD_DR_COMMENT (FAMILY_ID ASC)
LOGGING 
TABLESPACE "GEMDB_TEST" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL

--  Creating Unique Index
CREATE UNIQUE INDEX GEMDB_TEST.SYS_C0081158 ON GEMDB_TEST.PRCBUILD_DR_COMMENT (ID ASC) 
LOGGING 
TABLESPACE "GEMDB_TEST" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL

--  Creating Table
CREATE TABLE GEMDB_TEST.PRCBUILD_DR_COMMENT 
(
  ID NUMBER(11, 0) NOT NULL 
, FAMILY_ID NUMBER(11, 0) NOT NULL 
, DR_DATE NVARCHAR2(500) 
, DR_COMMENTS NVARCHAR2(2000) 
, LAST_UPDATED_BY NVARCHAR2(500) 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CREATED_BY NVARCHAR2(500) 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT SYS_C0081158 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "GEMDB_TEST" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL

--  Altering Table
ALTER TABLE GEMDB_TEST.PRCBUILD_DR_COMMENT
ADD CONSTRAINT SYS_C0081159 FOREIGN KEY
(
  FAMILY_ID 
)

-- References
REFERENCES GEMDB_TEST.PRCBUILD_DR_FAMILY
(
  ID 
)
DEFERRABLE INITIALLY DEFERRED
ENABLE
